from . import hotel_amenity
from . import hotel_room_type
from . import hotel_room
from . import hotel_rate_plan
from . import hotel_reservation
from . import hotel_folio
from . import hotel_housekeeping
from . import hotel_dashboard
from . import res_partner
from . import res_company
